services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8081:3000"
    hostname: "ordenes_de_servicio.local"
    container_name: ordenes_de_servicio
    image: ordenes_de_servicio
    restart: unless-stopped
    user: "node:node"
    volumes:
      - ./data/firmas:/app/uploads/firmas
      - ./data/avatares:/app/uploads/avatares
    depends_on:
      - db
    environment:
      ORIGIN: ${ORIGIN}
      PROTOCOL_HEADER: X-Forwarded-Proto
      HOST_HEADER: X-Forwarded-Host
      TZ: ${TIME_ZONE:-UTC}
      NODE_ENV: production
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}

  db:
    image: "mysql:9.5"
    ports:
      - "127.0.0.1:3311:3306"
    hostname: "ordenes_de_servicio-mysql.local"
    container_name: "ordenes_de_servicio-mysql.local"
    environment:
      TZ: ${TIME_ZONE:-UTC}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql

  migrate:
    build:
      context: .
      target: tools
    command: pnpm db:migrate
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - db
    profiles:
      - migrate

  seed:
    build:
      context: .
      target: tools
    command: node ./src/lib/server/db/seed.js
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - db
    profiles:
      - seed

volumes:
  mysqldata:
