services:
  db:
    image: "mysql:9.5"
    ports:
      - "${MYSQL_PORT_FORWARD}:3306"
    hostname: "ordenes_de_servicio-mysql-dev.local"
    container_name: "ordenes_de_servicio-mysql-dev.local"
    environment:
      TZ: ${TIME_ZONE:-UTC}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
