
export const BusinessRules = {

  EMPLEADO_REGISTRAR_NUMERO_EMPLEADO_DUPLICADO: 'EMPLEADO_REGISTRAR_NUEVO_EMPLEADO_DUPLICADO',

  USUARIO_CAMBIAR_PASSWORD_PASSWORD_ACTUAL_INCORRECTO: 'USUARIO_CAMBIAR_PASSWORD_PASSWORD_ACTUAL_INCORRECTO',
  USUARIO_NO_CONSULTAR_DETALLE_USUARIO_LOGUEADO: 'USUARIO_NO_CONSULTAR_DETALLE_USUARIO_LOGUEADO',

  EMPLEADO_NO_ENCONTRADO_EN_INVITACION: 'EMPLEADO_NO_ENCONTRADO_EN_INVITACION',
  ROL_NO_ENCONTRADO_EN_INVITACION: 'ROL_NO_ENCONTRADO_EN_INVITACION',
  SOLO_ADMINISTRADOR_PUEDE_REGISTRAR_OTRO_ADMINISTRADOR: 'SOLO_ADMINISTRADOR_PUEDE_REGISTRAR_OTRO_ADMINISTRADOR',
  EMPLEADO_YA_TIENE_USUARIO_O_INVITACION: 'EMPLEADO_YA_TIENE_USUARIO_O_INVITACION',
  TOKEN_NO_REGISTRADO_PARA_REGISTRO_USUARIO: 'TOKEN_NO_REGISTRADO_PARA_REGISTRO_USUARIO',
  TOKEN_YA_USADA_PARA_REGISTRO_USUARIO: 'TOKEN_YA_USADO_PARA_REGISTRO_USUARIO',
  NOMBRE_USUARIO_NO_DISPONIBLE: 'NOMBRE_USUARIO_NO_DISPONIBLE',
  NO_AGREGAR_AREAS_FUERA_DE_ALCANCE: 'NO_AGREGAR_AREAS_FUERA_DE_ALCANCE',

  EMPLEADO_NO_ENCONTRADO: 'EMPLEADO_NO_ENCONTRADO',
  AREA_SIN_ENCARGADO: 'AREA_SIN_ENCARGADO',

  ORDEN_DE_SERVICIO_NO_ENCONTRADA: 'ORDEN_DE_SERVICIO_NO_ENCONTRADA',
  ASIGNACION_FUERA_DE_ESTADO: 'ASIGNACION_FUERA_DE_ESTADO',
  DESASIGNACION_FUERA_DE_ESTADO: 'DESASIGNACION_FUERA_DE_ESTADO',
  SIN_AGENTES_EN_ORDEN_SERVICIO: 'SIN_AGENTES_EN_ORDEN_SERVICIO',
  NO_SE_PUEDE_ASIGNAR_USUARIO_COMO_AGENTE: 'NO_SE_PUEDE_ASIGNAR_USUARIO_COMO_AGENTE',
  AGENTE_OCUPADO_EN_OTRO_OS_EN_PROCESO: 'AGENTE_OCUPADO_EN_OTRO_OS_EN_PROCESO',
  CAMBIO_ESTADO_OS_OBSERVACION_OBLIGATORIA: 'CAMBIO_ESTADO_OS_OBSERVACION_OBLIGATORIA',
  FLUJO_CAMBIO_ESTADO_OS_INCORRECTO: 'FLUJO_CAMBIO_ESTADO_OS_INCORRECTO',
  AGREGACION_ACTIVO_FUERA_DE_ESTADO: 'AGREGACION_ACTIVO_FUERA_DE_ESTADO',
  ELIMINACION_ACTIVO_FUERA_DE_ESTADO: 'ELIMINACION_ACTIVO_FUERA_DE_ESTADO',
  MODIFICACION_DE_ORDEN_FUERA_DE_ESTADO: 'MODIFICACION_DE_ORDEN_FUERA_DE_ESTADO'

};
